project_id = "medymwrwazqbtuxpujls"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.external-api]
verify_jwt = false

[functions.track-session]
verify_jwt = false

[functions.invoice-status-notification]
verify_jwt = false
